sudo: required

services:
  - docker

compiler:
  - gcc

group: edge

before_install:
  - docker pull absalomedia/hhvm-newrelic-ext
  - docker ps -a
  - docker info

script:
  - docker build -t absalomedia/hhvm-newrelic-ext . 

notifications:
    on_success: never
    on_failure: never

os:
  - linux
